apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fscoding
  labels:
    app: fscoding
spec:
  selector:
    matchLabels:
      app: fscoding
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fscoding
    spec:
      containers:
      - image: fsadykov/dc-test
        name: fscoding
        ports:
        - containerPort: 5000
          name: fscoding
