apiVersion: v1
kind: Service
metadata:
  name: fscoding
  labels:
    app: fscoding
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: fscoding
  type: LoadBalancer
